import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import TopBar from '@/components/shared/TopBar'
import BottomBar from '@/components/shared/BottomBar'
import LeftSideBar from '@/components/shared/LeftSideBar'
import RightSideBar from '@/components/shared/RightSideBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <TopBar></TopBar>
        <main className='flex flex-row'>
            <LeftSideBar></LeftSideBar>
            <section className='main-container'>
                <div className='w-full max-w-4xl'>
                    {children}
                </div>

            </section>
            <RightSideBar></RightSideBar>
        </main>
        <BottomBar></BottomBar>
        </body>
    </html>
    </ClerkProvider>
  )
}
